SELECT  RDCDVC_SE_CD, RDCDVC_KND_CD, count(VIN) FROM vsysd.STD_DLM_TB_ERP_ATT_HIS
GROUP BY RDCDVC_SE_CD, RDCDVC_KND_CD
ORDER BY RDCDVC_SE_CD, RDCDVC_KND_CD;

SELECT VHCL_ERSR_YN, count(VIN) FROM vsysd.STD_CEG_CAR_MIG
GROUP BY VHCL_ERSR_YN;

SELECT count(*) FROM vsysd.STD_CEG_CAR_MIG;

SELECT DISTINCT(CLS_YMD) FROM vsysz.STD_CEG_GRD_LST;

SELECT count(*) FROM vsysz.STD_CEG_GRD_LST
WHERE CLS_YMD = (SELECT max(CLS_YMD) FROM vsysz.STD_CEG_GRD_LST);

SELECT count(*) FROM vsysz.STD_CEG_GRD_LST
WHERE CLS_YMD = '20231130';

-- 최신 한달 데이터만 추출
--EXPORT (SELECT count(*) FROM vsysz.STD_CEG_GRD_LST
--WHERE CLS_YMD = (SELECT max(CLS_YMD) FROM vsysz.STD_CEG_GRD_LST)) INTO LOCAL CSV FILE 'D:/data/processing/big3/raw/public/STD_CEG_GRD_LST_20240105_093400.csv'
--COLUMN SEPARATOR = '|';

SELECT DISTINCT(EXHST_GAS_GRD_CD) FROM vsysz.STD_CEG_GRD_LST
WHERE CLS_YMD = (SELECT max(CLS_YMD) FROM vsysz.STD_CEG_GRD_LST);

SELECT count(*) FROM vsysz.STD_CEG_GRD_LST
WHERE CLS_YMD = (SELECT max(CLS_YMD) FROM vsysz.STD_CEG_GRD_LST);

SELECT count(*) FROM vsysz.STD_CEG_GRD_LST
WHERE CLS_YMD = (SELECT max(CLS_YMD) FROM vsysz.STD_CEG_GRD_LST)
GROUP BY 
CLS_YMD
,VHCL_MNG_NO
,VHRNO
,BSPL_STDG_CD
,STDG_CTPV_NM
,STDG_SGG_NM
,VHCL_OWNR_CL_CD
,VHCTY_CD
,PURPS_CD2
,VIN
,FRST_REG_YMD
,YRIDNW
,VHCL_FBCTN_YMD
,EXTGAS_INSP_VLD_YMD
,EXHST_GAS_CERT_NO
,EXHST_GAS_GRD_CD
,LEM_KND_CD
,STRCT_CHG_YN
,VHCL_ERSR_YN
,MANP_MNG_NO
,VHCNM
,VHCTY_CL_CD
,VHCTY_TY_CD2
,VHCL_FRM
,MNFCTR_NM
,FUEL_CD
,FUEL_G_NM
,EGIN_TY
,TOTL_WGHT
,CRYNG_WGHT
,EGIN_OTPT
,DSPLVL
,TKCAR_PSCP
,OVRLH
,OVRWD
,OVRHG
,FBCTN_NTN_NM
,BOHUM_YN;

SELECT DISTINCT EXTGAS_GRNTE_WHL_TY FROM vsysd.STD_BD_CAR;

SELECT DISTINCT CRTR_YM FROM vsyse.STD_BD_GRD4_ELPDSRC_CURSTT;

SELECT DISTINCT LOAD_DT FROM vsyse.STD_BD_GRD4_ELPDSRC_CURSTT
WHERE CRTR_YM = '2023.1';

UPDATE vsyse.STD_BD_GRD4_ELPDSRC_CURSTT
SET CRTR_YM = '2023.10'
WHERE CRTR_YM = '2023.1'



SELECT DISTINCT CRTR_YM FROM vsyse.STD_BD_GRD5_ELPDSRC_CURSTT;

SELECT DISTINCT LOAD_DT FROM vsyse.STD_BD_GRD5_ELPDSRC_CURSTT
WHERE CRTR_YM = '2020.1';

UPDATE vsyse.STD_BD_GRD5_ELPDSRC_CURSTT
SET CRTR_YM = '2020.10'
WHERE CRTR_YM = '2020.1';

UPDATE vsyse.STD_BD_GRD5_ELPDSRC_CURSTT
SET CRTR_YM = '2021.04'
WHERE CRTR_YM = '2021.4';

UPDATE vsyse.STD_BD_GRD5_ELPDSRC_CURSTT
SET CRTR_YM = '2023.10'
WHERE CRTR_YM = '2023.1';

UPDATE vsyse.STD_BD_GRD5_ELPDSRC_CURSTT
SET CRTR_YM = '2019.10'
WHERE CRTR_YM = '2019.1';

UPDATE vsyse.STD_BD_GRD5_ELPDSRC_CURSTT
SET CRTR_YM = '2021.10'
WHERE CRTR_YM = '2021.1';

UPDATE vsyse.STD_BD_GRD5_ELPDSRC_CURSTT
SET CRTR_YM = '2022.10'
WHERE CRTR_YM = '2022.1';

SELECT DISTINCT CRTR_YM FROM vsyse.STD_BD_GRD5_RGN_CURSTT;

SELECT DISTINCT MM FROM vsyse.STD_BD_GRD5_RGN_CURSTT
WHERE CRTR_YM = '2023.1';

UPDATE vsyse.STD_BD_GRD5_RGN_CURSTT
SET CRTR_YM = '2023.10'
WHERE CRTR_YM = '2023.1';

SELECT DISTINCT CRTR_YM FROM vsyse.std_bd_grd5_car_curstt;

SELECT DISTINCT cls_ymd FROM vsysz.std_ceg_grd_lst;