--SELECT count(*) FROM "wabotech".STD_BD_GRD4_EXHST_GAS_MSS;

--SELECT * FROM "wabotech".STD_BD_CAR_CURSTT

-- 테이블 생성
-- 차량 현황
CREATE TABLE "wabotech".STD_BD_CAR_CURSTT(
	VIN VARCHAR2(120),
	BSPL_STDG_CD VARCHAR2(120),
	FUEL_CD VARCHAR2(120), 
	EXHST_GAS_GRD_CD VARCHAR2(200), 
	VHCTY_CD VARCHAR2(200)
);

-- 4등급차 말소 결과
CREATE TABLE "wabotech".STD_BD_GRD4_ERSR_RSLT(
	VIN VARCHAR2(120),
	BSPL_STDG_CD VARCHAR2(120),
	FUEL_CD VARCHAR2(120), 
	CHG_YMD VARCHAR2(120)
);

-- 4등급차 배출가스 량
CREATE TABLE "wabotech".STD_BD_GRD4_EXHST_GAS_MSS(
	VIN VARCHAR2(120),
	FUEL_CD VARCHAR2(120), 
	STDG_CD VARCHAR2(120),
	VHCTY_CD VARCHAR2(200),
	VHCTY_TY VARCHAR2(80),
	CO_EXHST_MSS FLOAT, 
	HC_EXHST_MSS FLOAT, 
	NOx_EXHST_MSS FLOAT, 
	PM10_EXHST_MSS FLOAT,
	PM2_5_EXHST_MSS FLOAT
);

-- 4등급차 세분류 결과
CREATE TABLE "wabotech".STD_BD_GRD4_MLSFC_RSLT(
	VIN VARCHAR2(120),
	STDG_CD VARCHAR2(120),
	YRIDNW VARCHAR2(40), 
	VHCTY_TY VARCHAR2(80),
	FUEL_CD VARCHAR2(120),
	GRD4_MLSFC VARCHAR2(40)
);

-- 4등급차 현황
CREATE TABLE "wabotech".STD_BD_GRD4_CAR_CURSTT(
	VIN VARCHAR2(120), 
	MANG_MNG_NO VARCHAR2(80),
	STDG_CD VARCHAR2(120),
	VHCTY_CD VARCHAR2(200),
	VHCTY_TY VARCHAR2(80),
	YRIDNW VARCHAR2(40), 
	FUEL_CD VARCHAR2(120),
	PURPS_CD2 VARCHAR2(120),
	MNFCTR_NM VARCHAR2(1600),
	VHCNM VARCHAR2(400),
	EXHST_GAS_CERT_NO_MOD VARCHAR2(200),
	DPF_MNTNG_YN VARCHAR2(40),
	INSP_MTHD VARCHAR2(120),
	INSP_KND VARCHAR2(120),
	NOLOD_SMO_MEVLU1 NUMBER,
	NOLOD_SMO_JGMT_YN1 VARCHAR2(1)
);

-- 파일 업로드
-- 차량 현황
IMPORT INTO	"wabotech".STD_BD_CAR_CURSTT  FROM LOCAL CSV FILE 'D:/data/big2/BD1/df/BD1_STD_BD_CAR_CURSTT.csv'

ROW	SEPARATOR = 'LF'

COLUMN SEPARATOR  = ','

SKIP = 1

ENCODING = 'UTF-8'

;

-- 4등급차 말소 결과
IMPORT INTO	"wabotech".STD_BD_GRD4_ERSR_RSLT FROM LOCAL CSV FILE 'D:/data/big2/BD1/df/BD1-2_STD_BD_GRD4_ERSR_RSLT.csv'

ROW	SEPARATOR = 'LF'

COLUMN SEPARATOR  = ','

SKIP = 1

ENCODING = 'UTF-8'

;

-- 4등급차 배출가스 량
IMPORT INTO	"wabotech".STD_BD_GRD4_EXHST_GAS_MSS FROM LOCAL CSV FILE 'D:/data/big2/BD1/df/BD1-3_STD_BD_GRD4_EXHST_GAS_MSS.csv'

ROW	SEPARATOR = 'CRLF'

COLUMN SEPARATOR  = ','

SKIP = 1

ENCODING = 'UTF-8'

;

-- 4등급차 세분류 결과
IMPORT INTO	"wabotech".STD_BD_GRD4_MLSFC_RSLT FROM LOCAL CSV FILE 'D:/data/big2/BD1/df/BD1-2_STD_BD_GRD4_MLSFC_RSLT.csv'

ROW	SEPARATOR = 'LF'

COLUMN SEPARATOR  = ','

SKIP = 1

ENCODING = 'UTF-8'

;

-- 4등급차 현황
IMPORT INTO	"wabotech".STD_BD_GRD4_CAR_CURSTT FROM LOCAL CSV FILE 'D:/data/big2/BD1/df/BD1-1_STD_BD_GRD4_CAR_CURSTT.csv'

ROW	SEPARATOR = 'LF'

COLUMN SEPARATOR  = ','

SKIP = 1

ENCODING = 'UTF-8'

;