-- 차량 말소 현황
CREATE TABLE "wabotech".STD_BD_ERSR_RSLT(
	VIN VARCHAR2(120),  
	FUEL_CD VARCHAR2(120),
	CHG_YMD VARCHAR2(120)
);

IMPORT INTO	"wabotech".STD_BD_ERSR_RSLT FROM LOCAL CSV FILE 'D:/data/big2/BD3/df/STD_BD_ERSR_RSLT.csv'

ROW	SEPARATOR = 'CRLF'

COLUMN SEPARATOR  = ','

SKIP = 1

ENCODING = 'UTF-8'

;

-- 저공해조치 및 운행제한
CREATE TABLE "wabotech".STD_BD_LEM_ND_RUN_LMT_CURSTT(
	VIN VARCHAR2(120),  
	FUEL_CD VARCHAR2(120)
);

IMPORT INTO	"wabotech".STD_BD_LEM_ND_RUN_LMT_CURSTT FROM LOCAL CSV FILE 'D:/data/big2/BD3/df/STD_BD_LEM_ND_RUN_LMT_CURSTT.csv'

ROW	SEPARATOR = 'CRLF'

COLUMN SEPARATOR  = ','

SKIP = 1

ENCODING = 'UTF-8'

;

-- 5등급 저공해조치 우선차량 선발차량 현황
CREATE TABLE "wabotech".STD_BD_GRD5_LEM_PRIO_ORD_SELCT_CURSTT(
	VIN VARCHAR2(120),
	BSPL_STDG_CD VARCHAR2(120),
	VHCTY_CD VARCHAR2(200),
	VHCTY_TY VARCHAR2(80),
	FUEL_CD VARCHAR2(120),	
	RDCDVC VARCHAR2(120),
	ECO_VLDT_ELPDSRC VARCHAR2(120),
	ECO_VLDT_DPF VARCHAR2(120),
	RCNT_INSP_ELPSD_WHL NUMBER,
	RUN_LMT_CRDN_YN VARCHAR2(8)
);

IMPORT INTO	"wabotech".STD_BD_GRD5_LEM_PRIO_ORD_SELCT_CURSTT FROM LOCAL CSV FILE 'D:/data/big2/BD3/df/STD_BD_GRD5_LEM_PRIO_ORD_SELCT_CURSTT.csv'

ROW	SEPARATOR = 'CRLF'

COLUMN SEPARATOR  = ','

SKIP = 1

ENCODING = 'UTF-8'

;

-- 4등급 저공해조치 우선차량 선발차량 현황
CREATE TABLE "wabotech".STD_BD_GRD4_LEM_PRIO_ORD_SELCT_CURSTT(
	VIN VARCHAR2(120),
	VHCTY_CD VARCHAR2(200),
	VHCTY_TY VARCHAR2(80),
	FUEL_CD VARCHAR2(120),
	STDG_CD VARCHAR2(120),
	RDCDVC VARCHAR2(120),
	ECO_VLDT VARCHAR2(120),
	RCNT_INSP_ELPSD_WHL NUMBER,
	RUN_LMT_CRDN_YN VARCHAR2(8)
);

IMPORT INTO	"wabotech".STD_BD_GRD4_LEM_PRIO_ORD_SELCT_CURSTT FROM LOCAL CSV FILE 'D:/data/big2/BD3/df/STD_BD_GRD4_LEM_PRIO_ORD_SELCT_CURSTT.csv'

ROW	SEPARATOR = 'CRLF'

COLUMN SEPARATOR  = ','

SKIP = 1

ENCODING = 'UTF-8'

;